"""alterando tabela transaction para date.today

Revision ID: b7d050480a6d
Revises: 23f3e872d760
Create Date: 2026-05-29 09:25:18.491631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d050480a6d'
down_revision: Union[str, Sequence[str], None] = '23f3e872d760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('date_transaction', sa.Date(), nullable=True))
    op.drop_constraint(op.f('transactions_id_category_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'categories', ['id_category'], ['id'], ondelete='RESTRICT')
    op.drop_column('transactions', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('data', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_id_category_fkey'), 'transactions', 'categories', ['id_category'], ['id'])
    op.drop_column('transactions', 'date_transaction')
    # ### end Alembic commands ###
